### ISSUE TITLE
Add  "password" authorizaton flow

### ISSUE THREAD

**Issue by chenghaoc** [ringcentral/ringcentral-cti-demo-js#5]
Currently the demo only support OAuth 2.0 for authorizaton which is considered harder to set up (need to configure the redirect URL).
Do you plan to add a demo about "password" authorizaton flow? It might be better for demo purpose.

**Comment by grokify** [comment]
There are no plans to implement OAuth 2.0 password grant flow (ROPC) in this particular demo because this is a client-side, in-browser demo that represents best practices. 3-legged OAuth 2.0 flows are best practices for client-side applications where there is little trust between the app and the resource owner. 3-legged OAuth 2.0 flows include authorization code and implicit grant. Password grant should not be used for 3rd-party, in-browser apps due to it's security model.

Differences between a 2-legged flow (ROPC) and 3-legged flow (Auth Code, Implicit Grant) include:
1. 3-legged flow is more secure since the app does not have access to resource owner credentials (e.g. password).
2. 3-legged flow supports SSO via SAML to other Identity Providers (IdPs) such as Okta, Ping, etc.

Because a 2-legged flow password grant requires the app receive the user's password credentials, a high degree of trust is required between the resource owner and the app and it is best suited for server-side apps, such as a backend authorization via a Node.js app, not a client-side in-browser authorization.

Services such as Google, Dropbox, Box, etc. only support 3-legged OAuth. Services such as Salesforce support password grant but only for server-side apps.

The code was originally developed with password grant but it has  it has been commented out because it is not best practices for a client-side app.

See more here:
- OAuth 2.0 ROPC flow: https://tools.ietf.org/html/rfc6749#section-1.3.3
- OAuth 2.0 Authorization Code flow: https://tools.ietf.org/html/rfc6749#section-1.3.1
